version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - "./nginx/conf/:/etc/nginx/conf.d/"
            - "./nginx/ssl/:/etc/nginx/certs"
            - "./../:/var/www/html"
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped

#    apache:
#        build: ./apache/
#        container_name: apache
#        depends_on:
#            - php
#            - mysql
#        ports:
#            - "80:80"
#            - "443:443"
#        restart: always
#        volumes:
#            - "./../:/var/www/html"

    php:
        container_name: php7.3
        build:
            context: ./php/
            dockerfile: Dockerfile-7.3
        restart: always
        volumes:
            - "./../:/var/www/html"

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8082:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: unless-stopped
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "8306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
